---
title: "RNA_3_import_plot_genes"
output: github_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

# RNA analysis

Start the analysis from the exported tables 

```{r message=FALSE}

rm(list=ls())

library(RColorBrewer)
library(tidyverse)



```

### Load settings

Colors, main directory 

```{r}

source('./r_inputs/TemporalSpatialNeuralTube_settings.R')

```


### Set dirs
```{r}

subworkinput="outputs_glialRNA_1/"

outdir="outputs_glialRNA_3_countplots/"
ifelse(!dir.exists(file.path(workingdir,outdir)), dir.create(file.path(workingdir,outdir)), "Directory exists")

```



## Load data

Load the normalized RNA counts table from RNA 1

```{r }

dds_counts <- read.table(paste0(workingdir,subworkinput,"featurecounts.normCounts.txt"),stringsAsFactors =FALSE)

```



## Tidy table

```{r}

dds_counts_plot <- dds_counts %>% 
  as.data.frame() %>%
  rownames_to_column("geneid") %>%
  gather(sampleid, counts_norm, MUT_D11_p1_NFIAn_R2:WT_D9_pM_NFIAp_R3) %>%
  separate(sampleid,into=c("Genotype","Day","Gate","NFIAgate","Rep"), sep="_", remove=FALSE) %>%
  mutate(Condition=paste(Genotype,Day,Gate,NFIAgate, sep="_"),
         DayNFIA=factor(paste(Day,NFIAgate,Genotype,sep = "_"), levels=sorted.dayNfia),
         NFIAstatus=paste(NFIAgate,Genotype,sep="_"),
         NFIAstatus=factor(NFIAstatus, levels = nfiaStatus_order),
         DayGate=factor(paste(Day,Gate,sep="_"), levels = sorted.DayGate),
         Experiment=paste(Genotype,Rep,sep="_"),
         Day=factor(Day, levels = sorted.day),
         Genotype=factor(Genotype, levels = c("WT","MUT")))

```


### Fig 5

```{r fig.width=6, fig.height=2}

geneOI <- c("Rasl11b")

genes_wt_ts <- ggplot(dds_counts_plot %>% filter(geneid %in% geneOI & Genotype=="WT") %>%
         mutate(geneid=factor(geneid, levels=geneOI)), 
        aes(x=Day,y=counts_norm)) +
  stat_summary(aes(fill=DayGate),
    fun = mean, geom="bar", alpha=0.8, width=0.7,position=position_dodge(0.7), color="black",linewidth=0.3) +
  geom_point(aes(fill=DayGate), alpha=0.9, position = position_dodge(width = 0.7),color="black", shape=21) +
  #geom_col(position="dodge",aes(fill=DayGate)) +
  scale_fill_manual(values=colorIZ) +
  scale_color_manual(values=colorIZ) +
  scale_shape_manual(values=shapes4_fill_manual) +
  facet_grid(geneid ~ Day, scales = "free") +
  theme_bw()

ggsave(plot=genes_wt_ts, filename=paste0(workingdir,outdir,"Barplots_genes_WT_timespace.pdf"), device = "pdf",
             width=6, height=2, units="in", useDingbats=FALSE)

genes_wt_ts

```

```{r fig.width=8, fig.height=2}
geneOI <- c("Adora1")

genes_ko <- ggplot(dds_counts_plot %>% filter(geneid %in% geneOI) %>%
         mutate(geneid=factor(geneid, levels=geneOI)), 
        aes(x=Day,y=counts_norm)) +
  stat_summary(aes(fill=DayGate),
    fun = mean, geom="bar", alpha=0.8, width=0.7,position=position_dodge(0.7), color="black",linewidth=0.3) +
  geom_point(aes(fill=DayGate), alpha=0.9, position = position_dodge(width = 0.7),color="black", shape=21) +
  #geom_col(position="dodge",aes(fill=DayGate)) +
  scale_fill_manual(values=colorIZ) +
  scale_color_manual(values=colorIZ) +
  scale_shape_manual(values=shapes4_fill_manual) +
  facet_grid(geneid ~ Genotype, scales = "free") +
  theme_bw()


ggsave(plot=genes_ko, filename=paste0(workingdir,outdir,"Barplots_genes_WT_KO.pdf"), device = "pdf",
             width=8, height=2, units="in", useDingbats=FALSE)

genes_ko
```


### fig 6

```{r fig.width=6, fig.height=2.5}

geneOI <- c("Olig1","Sox10","Mnx1","Isl1","Lhx3")

genes_NFIABKO <- ggplot(dds_counts_plot %>% filter(geneid %in% geneOI & Gate=="pM") %>%
         mutate(geneid=factor(geneid, levels=geneOI)), 
        aes(x=Day,y=counts_norm)) +
  stat_summary(aes(fill=Genotype),
    fun = mean, geom="bar", alpha=0.8, width=0.7,position=position_dodge(0.7), color="black",linewidth=0.3) +
  geom_point(aes(fill=Genotype), alpha=0.9, position = position_dodge(width = 0.7),color="black", shape=21) +
  scale_fill_manual(values=c("grey60","#e64466")) +
  scale_color_manual(values=c("grey60","#e64466")) +
  scale_shape_manual(values=shapes4_fill_manual) +
  facet_wrap(~ geneid , scales = "free") +
  theme_bw()

ggsave(plot=genes_NFIABKO, filename=paste0(workingdir,outdir,"Barplots_MNgenes_pMN_WT_KO.pdf"), device = "pdf",
             width=7, height=3, units="in", useDingbats=FALSE)

genes_NFIABKO

```
### Revision QC of model

Temporal and dorsoventral genes

```{r fig.width=6, fig.height=6}

geneOI <- c("Sox9","Nfia","Nfib","Slc1a3","Dbx1","Pax6","Foxn4","Nkx6-1","Olig2")

genes_qc <- ggplot(dds_counts_plot %>% filter(geneid %in% geneOI & Genotype=="WT") %>%
         mutate(geneid=factor(geneid, levels=geneOI)), 
        aes(x=Day,y=counts_norm)) +
  stat_summary(aes(fill=DayGate),
    fun = mean, geom="bar", alpha=0.8, width=0.7,position=position_dodge(0.7), color="black",linewidth=0.3) +
  geom_point(aes(fill=DayGate), alpha=0.9, position = position_dodge(width = 0.7),color="black", shape=21) +
  #geom_col(position="dodge",aes(fill=DayGate)) +
  scale_fill_manual(values=colorIZ) +
  scale_color_manual(values=colorIZ) +
  scale_shape_manual(values=shapes4_fill_manual) +
  facet_grid(geneid ~ Day, scales = "free") +
  theme_bw()


ggsave(plot=genes_qc, filename=paste0(workingdir,outdir,"Barplots_ESmodel_QC.pdf"), device = "pdf",
             width=6, height=6, units="in", useDingbats=FALSE)

genes_qc

```



```{r}
sessionInfo()
```